# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-04-03 17:22+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: core/Rpg.py:27
msgid "ERROR_UNKNOWN_SELECTED_WORLD"
msgstr ""

#: core/Rpg.py:45
msgid "PLAYER_SELECTION"
msgstr ""

#: core/Rpg.py:46
msgid "CHOICE_NEW_PLAYER"
msgstr ""

#: core/Rpg.py:47
msgid "CHOICE_EXISTING_PLAYER"
msgstr ""

#: core/Rpg.py:49
msgid "CHOICE_QUESTION"
msgstr ""

#: core/Rpg.py:144
msgid "COMMAND_PROMPT"
msgstr ""

#: core/command_factory.py:38 core/commands/help.py:38
#: tests/commands/help.py:26 tests/commands/help.py:61
#: tests/commands/look.py:15 tests/commands/look.py:34
msgid "LOOK_COMMAND"
msgstr ""

#: core/command_factory.py:39 core/commands/help.py:22
#: tests/commands/help.py:18 tests/commands/help.py:45
#: tests/commands/talk.py:14 tests/commands/talk.py:19
#: tests/commands/talk.py:24 tests/commands/talk.py:29
#: tests/commands/talk.py:34 tests/commands/talk.py:39
#: tests/commands/talk.py:44 tests/commands/talk.py:49
#: tests/commands/talk.py:54
msgid "TALK_COMMAND"
msgstr ""

#: core/command_factory.py:40 core/commands/help.py:26
#: tests/commands/help.py:20 tests/commands/help.py:49
#: tests/commands/move.py:14 tests/commands/move.py:19
#: tests/commands/move.py:24 tests/commands/move.py:29
#: tests/commands/move.py:34 tests/commands/move.py:39
#: tests/commands/move.py:44 tests/commands/move.py:49
msgid "MOVE_COMMAND"
msgstr ""

#: core/command_factory.py:41 core/commands/help.py:30
#: tests/commands/enter.py:14 tests/commands/enter.py:19
#: tests/commands/enter.py:24 tests/commands/enter.py:29
#: tests/commands/enter.py:34 tests/commands/enter.py:39
#: tests/commands/enter.py:44 tests/commands/enter.py:46
#: tests/commands/enter.py:51 tests/commands/enter.py:53
#: tests/commands/enter.py:58 tests/commands/enter.py:63
#: tests/commands/exit.py:53 tests/commands/exit.py:60
#: tests/commands/help.py:22 tests/commands/help.py:53
msgid "ENTER_COMMAND"
msgstr ""

#: core/command_factory.py:42 core/commands/help.py:34
#: tests/commands/exit.py:13 tests/commands/exit.py:18
#: tests/commands/exit.py:23 tests/commands/exit.py:28
#: tests/commands/exit.py:33 tests/commands/exit.py:38
#: tests/commands/exit.py:43 tests/commands/exit.py:48
#: tests/commands/exit.py:55 tests/commands/exit.py:62
#: tests/commands/help.py:24 tests/commands/help.py:57
msgid "EXIT_COMMAND"
msgstr ""

#: core/command_factory.py:43 core/commands/help.py:46
#: tests/commands/drop.py:55 tests/commands/drop.py:63
#: tests/commands/drop.py:71 tests/commands/drop.py:79
#: tests/commands/drop.py:87 tests/commands/drop.py:95
#: tests/commands/help.py:30 tests/commands/help.py:69
#: tests/commands/inventory.py:25 tests/commands/inventory.py:33
#: tests/commands/take.py:14 tests/commands/take.py:19
#: tests/commands/take.py:24 tests/commands/take.py:29
#: tests/commands/take.py:34 tests/commands/take.py:39
#: tests/commands/take.py:44 tests/commands/take.py:49
#: tests/commands/take.py:54 tests/commands/take.py:59
#: tests/commands/take.py:64 tests/commands/take.py:69
#: tests/commands/take.py:74 tests/commands/take.py:79
msgid "TAKE_COMMAND"
msgstr ""

#: core/command_factory.py:44 core/commands/help.py:50
#: tests/commands/drop.py:14 tests/commands/drop.py:19
#: tests/commands/drop.py:24 tests/commands/drop.py:29
#: tests/commands/drop.py:34 tests/commands/drop.py:39
#: tests/commands/drop.py:44 tests/commands/drop.py:49
#: tests/commands/drop.py:57 tests/commands/drop.py:65
#: tests/commands/drop.py:73 tests/commands/drop.py:81
#: tests/commands/drop.py:89 tests/commands/drop.py:97
#: tests/commands/help.py:32 tests/commands/help.py:73
msgid "DROP_COMMAND"
msgstr ""

#: core/command_factory.py:45 core/commands/help.py:42
#: tests/commands/help.py:28 tests/commands/help.py:65
#: tests/commands/inventory.py:14 tests/commands/inventory.py:19
#: tests/commands/inventory.py:27 tests/commands/inventory.py:35
msgid "INVENTORY_COMMAND"
msgstr ""

#: core/command_factory.py:46 core/commands/help.py:42
#: tests/commands/help.py:28 tests/commands/help.py:65
msgid "INVENTORY_SHORT_COMMAND"
msgstr ""

#: core/command_factory.py:47 core/commands/help.py:54
#: tests/commands/help.py:15 tests/commands/help.py:34
#: tests/commands/help.py:41 tests/commands/help.py:77
msgid "HELP_COMMAND"
msgstr ""

#: core/command_factory.py:73 core/commands/help.py:58
#: tests/commands/help.py:36 tests/commands/help.py:81
msgid "QUIT_COMMAND"
msgstr ""

#: core/command_factory.py:73 core/commands/help.py:58
#: tests/commands/help.py:36 tests/commands/help.py:81
msgid "QUIT_SHORT_COMMAND"
msgstr ""

#: core/command_factory.py:79
msgid "ERROR_UNKNOWN_COMMAND"
msgstr ""

#: core/commands/drop.py:17 tests/commands/drop.py:16
#: tests/commands/drop.py:21
msgid "ERROR_DROP_NO_ITEM_GIVEN"
msgstr ""

#: core/commands/drop.py:27 tests/commands/drop.py:46
#: tests/commands/drop.py:51
msgid "ERROR_DROP_INVALID_QUANTITY"
msgstr ""

#: core/commands/drop.py:34 tests/commands/drop.py:26
#: tests/commands/drop.py:31
msgid "ERROR_DROP_UNKNOWN_ITEM"
msgstr ""

#: core/commands/drop.py:39 tests/commands/drop.py:36
#: tests/commands/drop.py:41
msgid "ERROR_DROP_ITEM_NOT_AVAILABLE"
msgstr ""

#: core/commands/drop.py:41 tests/commands/drop.py:59
#: tests/commands/drop.py:67
#, python-format
msgid "ERROR_DROP_QUANTITY_TOO_HIGH_%s"
msgstr ""

#: core/commands/drop.py:50 tests/commands/drop.py:75
#: tests/commands/drop.py:91
#, python-format
msgid "DROP_CONFIRMATION_%(quantity)s_%(name)s"
msgstr ""

#: core/commands/enter.py:21 tests/commands/enter.py:16
#: tests/commands/enter.py:21
msgid "ERROR_ENTER_NO_PLACE_GIVEN"
msgstr ""

#: core/commands/enter.py:27 core/commands/exit.py:27
#: tests/commands/enter.py:26 tests/commands/enter.py:31
#: tests/commands/enter.py:48 tests/commands/enter.py:55
#: tests/commands/exit.py:25 tests/commands/exit.py:30
#: tests/commands/exit.py:45 tests/commands/exit.py:50
msgid "ERROR_ENTER_PLACE_NOT_AVAILABLE"
msgstr ""

#: core/commands/enter.py:33 tests/commands/enter.py:60
#: tests/commands/enter.py:65
msgid "ENTER_CONFIRMATION"
msgstr ""

#: core/commands/exit.py:21 tests/commands/exit.py:15
#: tests/commands/exit.py:20
msgid "ERROR_EXIT_NO_PLACE_GIVEN"
msgstr ""

#: core/commands/exit.py:31 tests/commands/exit.py:57
#: tests/commands/exit.py:64
msgid "EXIT_CONFIRMATION"
msgstr ""

#: core/commands/help.py:22 tests/commands/help.py:18
#: tests/commands/help.py:45
msgid "CHARACTER_TOKEN"
msgstr ""

#: core/commands/help.py:22 tests/commands/help.py:18
#: tests/commands/help.py:45
msgid "SENTENCE_TOKEN"
msgstr ""

#: core/commands/help.py:23 tests/commands/help.py:19
#: tests/commands/help.py:46
msgid "TALK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:27 tests/commands/help.py:21
#: tests/commands/help.py:50
msgid "MOVE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:31 tests/commands/help.py:23
#: tests/commands/help.py:54
msgid "ENTER_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:35 tests/commands/help.py:25
#: tests/commands/help.py:58
msgid "EXIT_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:39 tests/commands/help.py:27
#: tests/commands/help.py:62
msgid "LOOK_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:43 tests/commands/help.py:29
#: tests/commands/help.py:66
msgid "INVENTORY_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:46 core/commands/help.py:50 tests/commands/help.py:30
#: tests/commands/help.py:32 tests/commands/help.py:69
#: tests/commands/help.py:73
msgid "ITEM_NAME_TOKEN"
msgstr ""

#: core/commands/help.py:46 core/commands/help.py:50 tests/commands/help.py:30
#: tests/commands/help.py:32 tests/commands/help.py:69
#: tests/commands/help.py:73
msgid "QUANTITY_TOKEN"
msgstr ""

#: core/commands/help.py:47 tests/commands/help.py:31
#: tests/commands/help.py:70
msgid "TAKE_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:51 tests/commands/help.py:33
#: tests/commands/help.py:74
msgid "DROP_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:55 tests/commands/help.py:35
#: tests/commands/help.py:78
msgid "HELP_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:59 tests/commands/help.py:37
#: tests/commands/help.py:82
msgid "QUIT_COMMAND_DESCRIPTION"
msgstr ""

#: core/commands/help.py:64 tests/commands/help.py:17
msgid "AVAILABLE_COMMANDS_TITLE"
msgstr ""

#: core/commands/look.py:63 tests/commands/look.py:18
#, python-format
msgid "CURRENT_REGION_%s"
msgstr ""

#: core/commands/look.py:67 tests/commands/look.py:20
msgid "PRESENT_CHARACTERS"
msgstr ""

#: core/commands/look.py:73 tests/commands/look.py:23
msgid "AVAILABLE_DIRECTIONS"
msgstr ""

#: core/commands/look.py:79 tests/commands/look.py:26
msgid "AVAILABLE_PLACES"
msgstr ""

#: core/commands/look.py:85 tests/commands/look.py:29
msgid "AVAILABLE_ITEMS"
msgstr ""

#: core/commands/move.py:19 tests/commands/move.py:16
#: tests/commands/move.py:21
msgid "ERROR_MOVE_NO_DIRECTION_GIVEN"
msgstr ""

#: core/commands/move.py:23 tests/commands/move.py:26
#: tests/commands/move.py:31
#, python-format
msgid "ERROR_MOVE_INVALID_DIRECTION_%s"
msgstr ""

#: core/commands/move.py:30 tests/commands/move.py:36
#: tests/commands/move.py:41
msgid "ERROR_MOVE_DIRECTION_NOT_AVAILABLE"
msgstr ""

#: core/commands/move.py:37 tests/commands/move.py:46
#, python-format
msgid "MOVE_CONFIRMATION_%s"
msgstr ""

#: core/commands/take.py:11 tests/commands/take.py:16
#: tests/commands/take.py:21
msgid "ERROR_TAKE_NO_ITEM_GIVEN"
msgstr ""

#: core/commands/take.py:20 tests/commands/take.py:46
#: tests/commands/take.py:51
msgid "ERROR_TAKE_INVALID_QUANTITY"
msgstr ""

#: core/commands/take.py:27 tests/commands/take.py:26
#: tests/commands/take.py:31
msgid "ERROR_TAKE_UNKNOWN_ITEM"
msgstr ""

#: core/commands/take.py:34 tests/commands/take.py:36
#: tests/commands/take.py:41
msgid "ERROR_TAKE_ITEM_NOT_AVAILABLE"
msgstr ""

#: core/commands/take.py:37 tests/commands/take.py:56
#: tests/commands/take.py:61
msgid "ERROR_TAKE_QUANTITY_TOO_HIGH"
msgstr ""

#: core/commands/take.py:46 tests/commands/take.py:66
#: tests/commands/take.py:76
#, python-format
msgid "TAKE_CONFIRMATION_%(quantity)s_%(name)s"
msgstr ""

#: core/commands/talk.py:18 tests/commands/talk.py:16
#: tests/commands/talk.py:21
msgid "ERROR_TALK_NO_CHARACTER_GIVEN"
msgstr ""

#: core/commands/talk.py:20 tests/commands/talk.py:26
#: tests/commands/talk.py:31
msgid "ERROR_TALK_NO_SENTENCE_GIVEN"
msgstr ""

#: core/commands/talk.py:29 tests/commands/talk.py:36
#: tests/commands/talk.py:41
msgid "ERROR_TALK_UNKNOWN_CHARACTER"
msgstr ""

#: core/commands/talk.py:36 tests/commands/talk.py:46
msgid "ERROR_TALK_UNKNOWN_SENTENCE"
msgstr ""

#: models/area.py:20 tests/commands/look.py:24 tests/commands/look.py:37
#: tests/commands/move.py:44 tests/commands/move.py:46
#: tests/commands/move.py:49 tests/commands/move.py:51
msgid "DIRECTION_KEY_NORTH"
msgstr ""

#: models/area.py:21 tests/commands/move.py:34 tests/commands/move.py:39
msgid "DIRECTION_KEY_EAST"
msgstr ""

#: models/area.py:22
msgid "DIRECTION_KEY_SOUTH"
msgstr ""

#: models/area.py:23
msgid "DIRECTION_KEY_WEST"
msgstr ""

#: models/area.py:38
msgid "AREA_TYPE_DUNGEON"
msgstr ""

#: models/area.py:38
msgid "AREA_TYPE_LAND"
msgstr ""

#: models/place.py:15 models/place.py:29 models/place.py:39 models/place.py:49
#: tests/commands/enter.py:24 tests/commands/exit.py:23
#: tests/commands/exit.py:28
msgid "PLACE_TYPE_CAVE"
msgstr ""

#: models/place.py:15 models/place.py:27 models/place.py:37 models/place.py:47
#: tests/commands/enter.py:44 tests/commands/enter.py:46
#: tests/commands/enter.py:51 tests/commands/enter.py:53
#: tests/commands/enter.py:58 tests/commands/enter.py:63
#: tests/commands/exit.py:43 tests/commands/exit.py:48
#: tests/commands/exit.py:53 tests/commands/exit.py:55
#: tests/commands/exit.py:60 tests/commands/exit.py:62
msgid "PLACE_TYPE_DUNGEON"
msgstr ""

#: models/place.py:25 models/place.py:35 models/place.py:45
#: tests/commands/enter.py:36 tests/commands/enter.py:41
#: tests/commands/exit.py:35 tests/commands/exit.py:40
msgid "ERROR_UNKNOWN_PLACE_TYPE"
msgstr ""

#: models/place.py:96
msgid "ERROR_PLACE_GENERATION"
msgstr ""

#: models/player.py:35
msgid "ERROR_CONNECT_INVALID_CREDENTIALS"
msgstr ""

#: models/player.py:42
msgid "LOGIN_PROMPT"
msgstr ""

#: models/player.py:45
msgid "ERROR_SIGNUP_LOGIN_ALREADY_USED"
msgstr ""

#: models/player.py:50
msgid "PASSWORD_PROMPT"
msgstr ""

#: models/player.py:53
msgid "CONFIRM_PASSWORD_PROMPT"
msgstr ""

#: models/player.py:58
msgid "ERROR_SIGNUP_PASSWORDS"
msgstr ""

#: models/player.py:67
msgid "GENDER_SELECTION"
msgstr ""

#: models/player.py:73
msgid "GENDER_PROMPT"
msgstr ""

#: models/player.py:87
msgid "SPECIES_SELECTION"
msgstr ""

#: models/player.py:94
msgid "SPECIES_PROMPT"
msgstr ""
